---
  - name: Configure OpenShift 4.x deployment Enviornment
    hosts: localhost
    become: yes
    vars_files:
      #- playbooks/vars/all.yml
      #- playbooks/vars/vault.yml
      #- playbooks/vars/idm.yml
      #- playbooks/vars/ocp4.yml
    vars:
      admin_user: admin
      ocp4_version: 4.3.0
      ocp4_dependencies_version: "{{ ocp4_version[:3] }}"
      ocp4_image_version: "{{ ocp4_version[:3] + '.0' }}"
      project_dir: /home/admin/qubinode-installer
      pull_secret: "{{ project_dir }}/pull-secret.txt"
      vm_public_key: "/home/{{ admin_user }}/.ssh/id_rsa.pub"
      openshift_install_folder: ocp4
      openshift_install_dir: "{{ project_dir }}/{{ openshift_install_folder }}"
      ignition_files_dir: "{{ openshift_install_dir }}"
      ssh_ocp4_public_key: "{{ lookup('file', vm_public_key) }}"
      podman_webserver: qbn-httpd
      rhcos_webserver_img_name: rhcos-webserver
      dest_ignitions_web_directory: "{{ webserver_directory }}/{{ ocp4_dependencies_version }}/ignitions/"
      webserver_directory: /opt/qubinode_webserver
      webserver_dependencies: "{{ webserver_directory }}/{{ ocp4_dependencies_version }}"
      webserver_images: "{{ webserver_directory }}/{{ ocp4_dependencies_version }}/images"
      coreos_installer_kernel: "rhcos-{{ ocp4_image_version }}-x86_64-installer-kernel"
      coreos_installer_initramfs: "rhcos-{{ ocp4_image_version }}-x86_64-installer-initramfs.img"
      coreos_metal_bios: "rhcos-{{ ocp4_image_version }}-x86_64-metal.raw.gz"
      openshift_mirror: http://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp4_dependencies_version }}/{{ ocp4_image_version }}
      coreos_tmp_dir: /tmp/build_coreos_container
      tear_down: false
      virtinstall_dir: "{{ project_dir }}/rhcos-install/"
      domain: lunchnet.example
      public_domain: "{{ domain }}"
      ocp4_cluster_domain: "cloud.{{ domain }}"
      idm_hostname: qbn-dns01
      idm_admin_user: admin
      idm_admin_pwd: "redhat2019"
      idm_server_ip: 172.24.24.10
      dns_teardown: false
      idm_dns_forward_zone: "{{ ocp4_cluster_domain }}"
      idm_dns_reverse_zone: "50.168.192.in-addr.arpa."
      ipa_host: qbn-dns01.lunchnet.example
      dns_wildcard: "*.apps.{{ cluster_name }}"
      nat_gateway: "192.168.50.1"

    environment:
      IPA_HOST: "{{idm_hostname}}.{{ domain }}"
      IPA_USER: "{{ idm_admin_user }}"
      IPA_PASS: "{{ idm_admin_pwd }}"


 

    tasks:
    - name: run the role ocp4-kvm-deployer
      import_role:
        name: ocp4-kvm-deployer
